### ISSUE TITLE
how can I add files to the "watch" list?

### ISSUE THREAD

**Issue by chickenham** [AlmogBaku/grunt-hook#3]
I moved my own sass compiler into a custom package and wanted to add the files to the watch list.  I tried doing the following, but it is not working:

```
grunt.config.merge({
    watch: {
      sass: {
            files: paths.sass,
            tasks: ['sasscompile'],
            options: {
              livereload: true
            }            
        }
    }
});
```

Any ideas here?

**Comment by AlmogBaku** [comment]
take a look how I did it with https://github.com/AlmogBaku/mean-compass

(btw, by definition of grunt.. you need to define the task `sasscompile` too.. so I guess that's the problem)

**Comment by chickenham** [comment]
Got it - looks I had loaded my task too late (priority 11) - I changed the priority to -100 and it works
