### ISSUE TITLE
error when multiple packages have tasks

### ISSUE THREAD

**Issue by chickenham** [AlmogBaku/grunt-hook#4]
I have two custom packages that each have their own _Gruntfile.js and tasks.  Both tasks execute correctly when only 1 task is present.  However, when both are present, only the 1st task is loaded, and I get this error:

Loading "_Gruntfile.js" task...ERROR

> > Error: ENOENT, no such file or directory
> > Warning: Task "sasscompile" not found. Use --force to continue.

**Comment by AlmogBaku** [comment]
:O that's bizarre.. I'll investigate that. in the meanwhile- I found that it is work with `grunt --debug --verbose`
